[package]
name = "csv2json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
anyhow = "1.0.89"
serde = "1.0.210"
serde_json = "1.0.128"
